In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data=pd.read_csv("spam.csv")

In [4]:
data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
data.columns

Index(['Category', 'Message'], dtype='object')

In [8]:
data['class']=data["Category"].map({'ham':0,'spam':1})

In [9]:
data.head()

Category                                            Message  class
0      ham  Go until jurong point, crazy.. Available only ...      0
1      ham                      Ok lar... Joking wif u oni...      0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3      ham  U dun say so early hor... U c already then say...      0
4      ham  Nah I don't think he goes to usf, he lives aro...      0

In [30]:
x=data["Message"]

In [31]:
y=data["class"]

In [32]:
x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [33]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: class, Length: 5572, dtype: int64

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [35]:
cv=CountVectorizer()
x=cv.fit_transform(x)

In [36]:
x

<5572x8709 sparse matrix of type '<class 'numpy.int64'>'
	with 74098 stored elements in Compressed Sparse Row format>

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [41]:
x_train.shape

(4457, 8709)

In [42]:
x_test.shape

(1115, 8709)

In [43]:
y_train.shape

(4457,)

In [44]:
y_test.shape

(1115,)

In [46]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [47]:
model.fit(x_train,y_train)

MultinomialNB()

In [48]:
model.score(x_test,y_test)

0.9856502242152466

In [50]:
msg="You won $500"
data=[msg]
vect=cv.transform(data).toarray()

In [52]:
pred=model.predict(vect)

In [53]:
pred

array([1], dtype=int64)

In [54]:
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [60]:
msg="You won Car"
data=[msg]
vect=cv.transform(data).toarray()

In [61]:
pred=model.predict(vect)

In [62]:
pred

array([0], dtype=int64)

In [65]:
import pickle
pickle.dump(cv,open('vectorize.pkl',"wb"))
pickle.dump(model,open('spam.pkl',"wb"))